<h1>Practice Notebook: Maurice Harkless' Career Stats</h1>

Import packages

In [2]:
import csv
import pandas as pd
import numpy as np

Read the file - harkless_stats.csv - covert to a pandas dataframe and display it.

In [3]:
df = pd.read_csv('harkless_stats.csv')
df_harkless = pd.DataFrame(df)
df_harkless.head()

,Season,Age,Tm,Lg,Pos,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2012-13,19.0,ORL,NBA,SF,76.0,59.0,1974.0,260.0,564.0,...,0.570,122.0,213.0,335.0,50.0,88.0,62.0,69.0,144.0,625.0
1,2013-14,20.0,ORL,NBA,SF,80.0,41.0,1950.0,224.0,483.0,...,0.594,69.0,195.0,264.0,80.0,97.0,50.0,86.0,140.0,592.0
2,2014-15,21.0,ORL,NBA,SF,45.0,4.0,674.0,63.0,158.0,...,0.537,38.0,68.0,106.0,25.0,32.0,9.0,27.0,66.0,158.0
3,2015-16,22.0,POR,NBA,SF,78.0,14.0,1457.0,195.0,411.0,...,0.622,101.0,179.0,280.0,67.0,49.0,35.0,62.0,124.0,498.0
4,2016-17,23.0,POR,NBA,SF,77.0,69.0,2223.0,314.0,624.0,...,0.621,125.0,216.0,341.0,88.0,85.0,70.0,86.0,214.0,773.0